name: CI/CD - ms-auth

on:
  push:
    branches: [main, qa]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Login en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir y subir imagen a Docker Hub
      run: |
        docker build -t arieling/ms-auth .
        docker push arieling/ms-auth

    - name: Conectar a EC2 y desplegar contenedor
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "${{ secrets.ENV_FILE }}" > .env
          docker pull arieling/ms-auth
          docker stop ms-auth || true
          docker rm ms-auth || true
          docker run -d --name ms-auth \
            -p 3002:3002 \
            --env-file .env \
            arieling/ms-auth
